//app/src/main/java/com/papa/sbiwebbot/SbiSref.kt
//ver 1.02-32
package com.papa.sbiwebbot

/**
 * Auto-generated from crawl logs (sid=20260227_142419).
 * This file is for REPLAY / reference only.
 */
object SbiSref {
    const val SID: String = "20260227_142419"

    data class Selector(val type: String, val v: String)
    data class Trigger(val text: String, val score: Int)
    data class Pin(
        val pinId: String,
        val fromUrl: String,
        val toUrl: String,
        val selectors: List<Selector>,
        val trigger: Trigger,
        val tsMs: Long,
    )

    val PINS: List<Pin> = listOf(
        Pin(
            pinId = "PIN_0002",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-high%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-high%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='salesval']"), Selector("text", "売買代金"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-high%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on")),
            trigger = Trigger(text = "売買代金", score = 0),
            tsMs = 1772169886944L,
        ),
        Pin(
            pinId = "PIN_0004",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-high%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='price']"), Selector("text", "値動き"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on")),
            trigger = Trigger(text = "値動き", score = 1),
            tsMs = 1772169933238L,
        ),
        Pin(
            pinId = "PIN_0006",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-upmargin%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downrate%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='downrate']"), Selector("text", "値下がり率（％）"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downrate%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on")),
            trigger = Trigger(text = "値下がり率（％）", score = 2),
            tsMs = 1772169945391L,
        ),
        Pin(
            pinId = "PIN_0008",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downrate%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downmargin%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='downmargin']"), Selector("text", "値下がり幅"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downmargin%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on")),
            trigger = Trigger(text = "値下がり幅", score = 2),
            tsMs = 1772169951254L,
        ),
        Pin(
            pinId = "PIN_0010",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-high%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-inc%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='inc']"), Selector("text", "出来高急増"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-inc%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on")),
            trigger = Trigger(text = "出来高急増", score = 1),
            tsMs = 1772169959792L,
        ),
        Pin(
            pinId = "PIN_0013",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-high%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-inc%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='inc']"), Selector("text", "売買代金急増"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-inc%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on")),
            trigger = Trigger(text = "売買代金急増", score = 0),
            tsMs = 1772169970563L,
        ),
        Pin(
            pinId = "PIN_0015",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-inc%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='stock']"), Selector("text", "国内株式"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on")),
            trigger = Trigger(text = "国内株式", score = 0),
            tsMs = 1772169980837L,
        ),
        Pin(
            pinId = "PIN_0017",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='mktT2']"), Selector("text", "東証スタンダード"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on")),
            trigger = Trigger(text = "東証スタンダード", score = 0),
            tsMs = 1772169991090L,
        ),
        Pin(
            pinId = "PIN_0019",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-upmargin%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='upmargin']"), Selector("text", "値上がり幅"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-upmargin%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on")),
            trigger = Trigger(text = "値上がり幅", score = 2),
            tsMs = 1772169995865L,
        ),
        Pin(
            pinId = "PIN_0021",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-upmargin%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downrate%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='downrate']"), Selector("text", "値下がり率（％）"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downrate%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on")),
            trigger = Trigger(text = "値下がり率（％）", score = 2),
            tsMs = 1772170000772L,
        ),
        Pin(
            pinId = "PIN_0023",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downmargin%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='stock']"), Selector("text", "国内株式"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on")),
            trigger = Trigger(text = "国内株式", score = 0),
            tsMs = 1772170026643L,
        ),
        Pin(
            pinId = "PIN_0025",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-upmargin%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='upmargin']"), Selector("text", "値上がり幅"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-upmargin%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on")),
            trigger = Trigger(text = "値上がり幅", score = 2),
            tsMs = 1772170030382L,
        ),
        Pin(
            pinId = "PIN_0027",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downrate%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downmargin%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='downmargin']"), Selector("text", "値下がり幅"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downmargin%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on")),
            trigger = Trigger(text = "値下がり幅", score = 2),
            tsMs = 1772170039651L,
        ),
        Pin(
            pinId = "PIN_0030",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-high%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-high%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='mktT2']"), Selector("text", "東証スタンダード"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-high%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on")),
            trigger = Trigger(text = "東証スタンダード", score = 0),
            tsMs = 1772170056069L,
        ),
        Pin(
            pinId = "PIN_0033",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='mktTM']"), Selector("text", "東証グロース"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on")),
            trigger = Trigger(text = "東証グロース", score = 0),
            tsMs = 1772170070628L,
        ),
        Pin(
            pinId = "PIN_0035",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-upmargin%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downrate%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='downrate']"), Selector("text", "値下がり率（％）"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-downrate%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on")),
            trigger = Trigger(text = "値下がり率（％）", score = 2),
            tsMs = 1772170079831L,
        ),
        Pin(
            pinId = "PIN_0038",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-high%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='turnover']"), Selector("text", "出来高"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-high%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on")),
            trigger = Trigger(text = "出来高", score = 1),
            tsMs = 1772170092674L,
        ),
        Pin(
            pinId = "PIN_0040",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-high%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-inc%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='inc']"), Selector("text", "出来高急増"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-inc%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on")),
            trigger = Trigger(text = "出来高急増", score = 1),
            tsMs = 1772170096123L,
        ),
        Pin(
            pinId = "PIN_0043",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-high%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='turnover']"), Selector("text", "出来高"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-high%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on")),
            trigger = Trigger(text = "出来高", score = 1),
            tsMs = 1772170108312L,
        ),
        Pin(
            pinId = "PIN_0045",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-high%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-inc%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='inc']"), Selector("text", "出来高急増"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-turnover%7Ctl4-inc%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on")),
            trigger = Trigger(text = "出来高急増", score = 1),
            tsMs = 1772170112872L,
        ),
        Pin(
            pinId = "PIN_0048",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-high%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-high%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='mktT2']"), Selector("text", "東証スタンダード"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-high%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on")),
            trigger = Trigger(text = "東証スタンダード", score = 0),
            tsMs = 1772170125340L,
        ),
        Pin(
            pinId = "PIN_0050",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-high%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-inc%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='inc']"), Selector("text", "売買代金急増"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-inc%7Ctl5-priceview%7Ctl7-T2&file=index.html&getFlg=on")),
            trigger = Trigger(text = "売買代金急増", score = 0),
            tsMs = 1772170131547L,
        ),
        Pin(
            pinId = "PIN_0053",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-high%7Ctl5-priceview%7Ctl7-T1&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-high%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='mktTM']"), Selector("text", "東証グロース"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-high%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on")),
            trigger = Trigger(text = "東証グロース", score = 0),
            tsMs = 1772170149088L,
        ),
        Pin(
            pinId = "PIN_0055",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-high%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            toUrl = "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-inc%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on",
            selectors = listOf(Selector("xpath", "//*[@id='inc']"), Selector("text", "売買代金急増"), Selector("href", "https://www.sbisec.co.jp/ETGate/?_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_DataStoreID=DSWPLETmgR001Control&_ActionID=DefaultAID&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-salesval%7Ctl4-inc%7Ctl5-priceview%7Ctl7-TM&file=index.html&getFlg=on")),
            trigger = Trigger(text = "売買代金急増", score = 0),
            tsMs = 1772170154340L,
        ),
        Pin(
            pinId = "PIN_0060",
            fromUrl = "https://site0.sbisec.co.jp/marble/domestic/top.do?_scpr=intpr",
            toUrl = "https://www.sbisec.co.jp/ETGate/?OutSide=on&getFlg=on&_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_ActionID=DefaultAID&_DataStoreID=DSWPLETmgR001Control&burl=iris_index&cat1=market&cat2=index&dir=tl1%2didx%7ctl2%2dstockIdx&file=index.html",
            selectors = listOf(Selector("xpath", "//body[1]/nav[2]/ul[2]/li[4]/a[1]"), Selector("text", "ランキング"), Selector("href", "https://www.sbisec.co.jp/ETGate/?OutSide=on&getFlg=on&_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_ActionID=DefaultAID&_DataStoreID=DSWPLETmgR001Control&burl=iris_ranking&cat1=market&cat2=ranking&dir=tl1-rnk%7Ctl2-stock%7Ctl3-price%7Ctl4-uprate%7Ctl5-priceview%7Ctl7-T1&file=index.html&_scpr=intpr=hn_i_ds_rank&_gl=1*vi1vfq*_gcl_au*MTc3MDE1NDg0Ny4xNzcyMDk2ODE3*_ga*MTY1NDk5NzQuMTc3MjA5NjgyNQ..*_ga_2X743H1G05*czE3NzIxNjk4ODAkbzMkZzEkdDE3NzIxNzAxODUkajU5JGwwJGgw")),
            trigger = Trigger(text = "ランキング", score = 1),
            tsMs = 1772170209015L,
        ),
        Pin(
            pinId = "PIN_0062",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?OutSide=on&getFlg=on&_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_ActionID=DefaultAID&_DataStoreID=DSWPLETmgR001Control&burl=iris_index&cat1=market&cat2=index&dir=tl1%2didx%7ctl2%2dstockIdx&file=index.html",
            toUrl = "https://www.sbisec.co.jp/ETGate/?OutSide=on&getFlg=on&_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_ActionID=DefaultAID&_DataStoreID=DSWPLETmgR001Control&burl=iris_index&cat1=market&cat2=index&dir=tl1%2didx%7ctl2%2dstockIdx&file=index.html#",
            selectors = listOf(Selector("xpath", "//body[1]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/a[1]"), Selector("text", "株価指数先物"), Selector("href", "https://www.sbisec.co.jp/ETGate/?OutSide=on&getFlg=on&_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_ActionID=DefaultAID&_DataStoreID=DSWPLETmgR001Control&burl=iris_index&cat1=market&cat2=index&dir=tl1%2didx%7ctl2%2dstockIdx&file=index.html#")),
            trigger = Trigger(text = "株価指数先物", score = 1),
            tsMs = 1772170220220L,
        ),
        Pin(
            pinId = "PIN_0064",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?OutSide=on&getFlg=on&_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_ActionID=DefaultAID&_DataStoreID=DSWPLETmgR001Control&burl=iris_index&cat1=market&cat2=index&dir=tl1%2didx%7ctl2%2dstockIdx&file=index.html#",
            toUrl = "https://www.sbisec.co.jp/ETGate/?OutSide=on&getFlg=on&_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_ActionID=DefaultAID&_DataStoreID=DSWPLETmgR001Control&burl=iris_index&cat1=market&cat2=index&dir=tl1%2didx%7ctl2%2dstockIdx&file=index.html#",
            selectors = listOf(Selector("xpath", "//body[1]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[7]/a[1]"), Selector("text", "国内市場概況"), Selector("href", "https://www.sbisec.co.jp/ETGate/?OutSide=on&getFlg=on&_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_ActionID=DefaultAID&_DataStoreID=DSWPLETmgR001Control&burl=iris_index&cat1=market&cat2=index&dir=tl1%2didx%7ctl2%2dstockIdx&file=index.html#")),
            trigger = Trigger(text = "国内市場概況", score = 0),
            tsMs = 1772170230014L,
        ),
        Pin(
            pinId = "PIN_0067",
            fromUrl = "https://www.sbisec.co.jp/ETGate/?OutSide=on&getFlg=on&_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_ActionID=DefaultAID&_DataStoreID=DSWPLETmgR001Control&burl=iris_index&cat1=market&cat2=index&dir=tl1%2didx%7ctl2%2dstockIdx&file=index.html#",
            toUrl = "https://www.sbisec.co.jp/ETGate/?OutSide=on&getFlg=on&_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_ActionID=DefaultAID&_DataStoreID=DSWPLETmgR001Control&burl=iris_economicCalendar&cat1=market&cat2=economicCalender&dir=tl1-cal%7Ctl2-schedule%7Ctl3-stock%7Ctl4-calsel&file=index.html",
            selectors = listOf(Selector("xpath", "//body[1]/table[1]/tbody[1]/tr[1]/td[1]/nav[1]/section[1]/ul[1]/li[17]/ul[1]/li[1]/a[1]"), Selector("text", "国内株式"), Selector("href", "https://www.sbisec.co.jp/ETGate/?OutSide=on&getFlg=on&_ControlID=WPLETmgR001Control&_PageID=WPLETmgR001Mdtl20&_ActionID=DefaultAID&_DataStoreID=DSWPLETmgR001Control&burl=iris_economicCalendar&cat1=market&cat2=economicCalender&dir=tl1-cal%7Ctl2-schedule%7Ctl3-stock%7Ctl4-calsel&file=index.html")),
            trigger = Trigger(text = "国内株式", score = 0),
            tsMs = 1772170240901L,
        ),
    )
}